force-app/main/default/objects/Account_History__c/Account_History__c.object-meta.xml
<CustomObject>
    <label>Account History</label>
    <nameField>
        <displayFormat>AH-{0000}</displayFormat>
        <label>Account History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Histories</relationshipLabel>
    <relationshipName>Account_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_History__c/fields/Field_API_name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_name__c</fullName>
    <label>Field API name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_History__c/fields/New_value__c.field-meta.xml
<CustomField>
    <fullName>New_value__c</fullName>
    <label>New value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_History__c/fields/Old_value__c.field-meta.xml
<CustomField>
    <fullName>Old_value__c</fullName>
    <label>Old value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountHistoryDAO.cls
public class AccountHistoryDAO {
    @AuraEnabled
    public static List<Account_History__c> getAccountHistoriesFromAccount(String id){
        List<Account_History__c> accountHistories =  [
            SELECT Account__c, Field_label__c, Field_API_name__c, Old_value__c, New_value__c, CreatedById, CreatedBy.Name, CreatedDate
            FROM Account_History__c
            WHERE Account__c = :id
            ORDER BY CreatedDate DESC
        ];
        return accountHistories.isEmpty() ? null : accountHistories;
    }
}