force-app/main/default/objects/Account_History__c/Account_History__c.object-meta.xml
<CustomObject>
    <label>Account History</label>
    <nameField>
        <displayFormat>AH-{0000}</displayFormat>
        <label>Account History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Histories</relationshipLabel>
    <relationshipName>Account_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Account_History__c/fields/Field_API_name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_name__c</fullName>
    <label>Field API name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_History__c/fields/New_value__c.field-meta.xml
<CustomField>
    <fullName>New_value__c</fullName>
    <label>New value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_History__c/fields/Old_value__c.field-meta.xml
<CustomField>
    <fullName>Old_value__c</fullName>
    <label>Old value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountService.cls
public class AccountService {

    public static void createAccountHistory(List<Account> newAccounts, Map<Id, Account> oldAccountsMap) {

        List<Account_History__c> allAccountHistories = new List<Account_History__c>();

        for(Account newAccount : newAccounts){
            allAccountHistories.addAll(getDifference(newAccount, oldAccountsMap.get(newAccount.Id)));
        }

        insert allAccountHistories;
    }

    public static List<Account_History__c> getDifference(Account newAccount, Account oldAccount){

        Schema.SObjectType objType = newAccount.getSObjectType(); 
        Map<String, Schema.SObjectField> fieldNameMap = Schema.SObjectType.Account.fields.getMap(); 
        List<Account_History__c> accountHistories = new List<Account_History__c>();

        for (String fieldName : fieldNameMap.keyset()) {

            if(newAccount.get(fieldName) != oldAccount.get(fieldName)){ 

                Account_History__c accountHistory = new Account_History__c(
                    Account__c = newAccount.Id,
                    Old_value__c = String.valueOf(oldAccount.get(fieldName)),
                    New_value__c = String.valueOf(newAccount.get(fieldName)),
                    Field_API_name__c = fieldName,
                    Field_label__c = fieldNameMap.get(fieldName).getDescribe().getLabel()
                );

                accountHistories.add(accountHistory);
            }
        }
        return accountHistories;
    }
}