force-app/main/default/objects/Account_History__c/Account_History__c.object-meta.xml
<CustomObject>
    <label>Account History</label>
    <nameField>
        <displayFormat>AH-{0000}</displayFormat>
        <label>Account History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_History__c/fields/New_value__c.field-meta.xml
<CustomField>
    <fullName>New_value__c</fullName>
    <label>New value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountServiceTest.cls
@isTest
public class AccountServiceTest {
    
    @TestSetup
    static void makeData(){
        Account account = new Account(Name = 'Test Name');
        insert account;
    }

    @isTest 
    static void testHistory(){
        Account account = [SELECT id, Name FROM Account LIMIT 1];
        account.Name = 'Test Updated';
        update account;

        List<Account_History__c> histories = AccountHistoryDAO.getAccountHistoriesFromAccount(account.id);
        System.assertEquals(histories[0].New_value__c, 'Test Updated');        
    }
}